### ISSUE TITLE
[Request] Use Airplane-Purpur as upstream

### ISSUE THREAD

**Issue by NovaPixell** [SugarcaneMC/Sugarcane#14]
Many big servers need Purpur implementation. Purpur is also very stable and a lot of servers owner need it. 
Please consider it :D

**Comment by Disguys** [comment]
I think that Sugarcane needs to create a new branch that will support Purpur, since everyone has different tastes.

**Comment by nevetS-718** [comment]
As Purpur has already quite against our project, we don't want the same thing that was speculated to happen with yatopia with code being used that would break our software. We are still deciding how we want to go about using Purpur in our software.

**Comment by NovaPixell** [comment]
Ok. But please really consider it.

**Comment by ghost** [comment]
I think thats a great idea. Purpur offers many advanced configuration settings and is very stable

**Comment by gvmii** [comment]
I completely agree. Purpur would make Sugarcane 10 times better.

**Comment by Toffikk** [comment]
Im gonna create an purpur branch or maybe we’re even gonna rebase on it , when Airplane updates their purpur branch to 1.17

**Comment by Toffikk** [comment]
done, see `1.17/purpur` branch
