### ISSUE TITLE
[Feature Request] Add ability to disable the "0005-Disable-reload-command" patch in the sugarcane.yml config

### ISSUE THREAD

**Issue by Disguys** [SugarcaneMC/Sugarcane#16]
Hello, I offer the function of the ability to disable the patch "[0005-Disable-reload-command](https://github.com/SugarcaneMC/Sugarcane/blob/ver/1.17/patches/api/0005-Disable-reload-command.patch)" in the sugarcane.yml config, because most plugin developers very often use the  command `/reload confirm`, and because of this patch, us have to use other software for the server, I would be very grateful if you add this feature.

**Comment by Toffikk** [comment]
You can use the `-DSugarcane.DisableReloadCommand=true` jvm arg , to enable the reload command

**Comment by Toffikk** [comment]
`false` not `true`

**Comment by Toffikk** [comment]
`-DSugarcane.DisableReloadCommand=false` to enable /reload

**Comment by Disguys** [comment]
thanks

**Comment by MrIvanPlays** [comment]
you boomers why did you reveal the secret of a patch i firstly implemented in yatopia?
