### ISSUE TITLE
0016-Heavily-optimize-furnance-fuel-and-recipe-lookups.patch is not doing anything

### ISSUE THREAD

**Issue by Fox2Code** [SugarcaneMC/Sugarcane#24]
I do not use Sugarcane as my server, but by checking the patches I found a patch that is not doing anything.
[0016-Heavily-optimize-furnance-fuel-and-recipe-lookups.patch](https://github.com/SugarcaneMC/Sugarcane/blob/1.17/rc/patches/server/0016-Heavily-optimize-furnance-fuel-and-recipe-lookups.patch)

A few days ago I assumed it's because the server didn't finished to port the patches from Yatopia. 
But by noticing the problem is still here, I decided to report the problem in case no one noticed.

**Comment by Kylepoops** [comment]
Thanks you for reporting this, we'll look into it

**Comment by Toffikk** [comment]
~~Did this patch work in Yatopia?~~ lol

**Comment by Fox2Code** [comment]
@Toffikk the issue has not been resolved?
I checked the last commit and the issue is not resolved.
If it can help you the patch come from this mod:
https://github.com/Shadows-of-Fire/FastFurnace
And there are also a variant for the crafting table:
https://github.com/Shadows-of-Fire/FastWorkbench

**Comment by Kylepoops** [comment]
Re-open because the issues hasn't been solved

**Comment by Kylepoops** [comment]
Closed because the patch has been dropped
