### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by iceBear67** [SugarcaneMC/Sugarcane#26]
Hi, developers! I'm a little bit curious about this project.  
Whats the `optimizations`  that will be added into this project?   
and where is the  `CONTRIBUTING.md`? :)

**Comment by Kylepoops** [comment]
You can view all our patches in [here](https://github.com/SugarcaneMC/Sugarcane/tree/1.17/rc/patches)
We don't have the `CONTRIBUTING.md` yet but there will be one in the future

**Comment by gvmii** [comment]
https://github.com/SugarcaneMC/Sugarcane/commit/00901a951dab9c3cf723c2f7a2caf821e083b093 Done.
