### ISSUE TITLE
Spawning broken on newest build

### ISSUE THREAD

**Issue by Sialss** [SugarcaneMC/Sugarcane#32]
### Expected behavior

Join game and have spawn on correct place

### Actual behavior

Fall through floor get many errors of packets not working

### Steps to reproduce

Join server

### Plugin list

none

### Agreements

- [X] I am running the latest version of Sugarcane.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Sugarcane.

**Comment by Kylepoops** [comment]
> get many errors of packets not working

Can you provide the logs? Thanks~

**Comment by Toffikk** [comment]
I can't reproduce this issue

**Comment by gvmii** [comment]
This sounds like a keepalive packet issue? Something happened in my server for a while, when i was having a lot of lag. Could you check your internet connection?

**Comment by Toffikk** [comment]
can you paste the output of `/version` and your server/client logs?

**Comment by Toffikk** [comment]
This issue can only be reproduced with a very high ping, and since you didn’t provide the output of `/version` and logs , this issue will be closed
