### ISSUE TITLE
[Feature Request] Console output prefix customization

### ISSUE THREAD

**Issue by ghost** [SugarcaneMC/Sugarcane#4]
Add a possibility to customize this [hh:mm:ss INFO/WARN/ERROR] prefix in console (e. g. remove time, brackets or message type or even add your own text.

**Comment by ghost** [comment]
i suggest low priority for the addition of this feature

**Comment by MrIvanPlays** [comment]
not possible. the alternative to the log4j.xml file ( that's how it's called in waterfall ) is shaded in the jar and the only way you can customize stuff is to edit the jar.

**Comment by Toffikk** [comment]
Out of scope for now
